#!/usr/bin/python3
import sys
import os
try:
	arg=''
	for i in range(1, len(sys.argv)):
		arg+=sys.argv[i]+' '
	if arg=='':
		raise Exception
	os.system('firefox --private-window "https://duckduckgo.com/?q='+arg+'"')
except Exception as e:
	print('Please enter text to search')